app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("my_account/", views.my_account, name="my_account"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("recipe-detail/<slug:slug>", views.recipe_detail, name="recipe_detail"),
    path("post-recipe/", views.post_recipe, name="post_recipe"),
    path("update-recipe/<slug:slug>", views.update_recipe, name="update_recipe"),
    path("delete-recipe/<slug:slug>", views.delete_recipe, name="delete_recipe"),
    path("edit-profile/", views.edit_profile, name="edit_profile"),
    path("add-profile-picture/", views.add_profile_picture, name="add_profile_picture"),
    path("register/", views.register, name="register"),
    path("verify-otp", views.is_verified, name="verify_otp"),
    path("posts", views.posts, name="posts"),
    path("posts/<slug:slug>", views.post_details, name="post_details"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("django.contrib.auth.urls")),
    # path("login/", LoginView.as_view(), name="login"),
    # path("logout/", LogoutView.as_view(), name="logout"),
    # path("password_reset/", PasswordResetView.as_view(), name="password_reset"),
    # path(
    #     "password_reset/done/",
    #     PasswordResetDoneView.as_view(template_name="password_reset_done.html"),
    #     name="password_reset_confirm",
    # ),
    path("verification/", include("verify_email.urls")),
    path("", include("app.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .utils import generate_slug

# Create your models here.


class UserProfileModel(AbstractUser):

    email = models.EmailField(blank=True, null=True, unique=True)
    profile_picture = models.ImageField(
        upload_to="profile_picture", blank=True, null=True
    )

    otp = models.IntegerField(blank=True, null=True)
    valid_till = models.DateTimeField(blank=True, null=True)

    def get_full_name(self):
        return super().get_full_name()

    def __str__(self):
        return self.username


class RecipeModel(models.Model):
    author = models.ForeignKey(UserProfileModel, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    type = models.CharField(max_length=100)
    picture = models.ImageField(
        upload_to="food_picture/", blank=False, null=False, default=""
    )
    ingredients = models.TextField(blank=False, null=False, default="")
    instructions = models.TextField(blank=False, null=False, default="")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique=True, blank=True, null=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = generate_slug(self.title)
        super().save(*args, **kwargs)

app/templates/app/add_profile_pic.html
{% extends 'base.html' %} {% load static %} {% block page_title %}Add Profile Picture{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <h2>Add Profile Picture</h2>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form|crispy }}
          <button type="submit" class="btn btn-primary">Save Changes</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/app/create_post.html
{% extends "base.html" %}

{% block page_title %}
Create Post
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <form method="post" class="form-group" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}

                    <button type="submit" class="btn btn-success">Create</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/app/dashboard.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}
    Dashboard
{% endblock %}

{% block css_files %}
    <link rel="stylesheet" href="{% static 'app/css/dashboard.css' %}">

{% endblock %}

{% block js_files %}
    <script defer src="{% static 'app/js/dashboard.js' %}"></script>
{% endblock %}

{% block content %}
    {% include "app/includes/navbar.html" %}

    <div class="container my-4">
        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
            {% for recipe in recipes %}
                <div class="col mb-4">
                    <div class="card h-100">
                        <img src="{% if recipe.picture %}{{recipe.picture.url}}{% endif %}" class="card-img-top img-fluid" alt="{{recipe.title}}">
                        <div class="card-body">
                            <h5 class="card-title">{{recipe.title}}</h5>
                            <!-- Add more information here if needed -->
                            <div class="text-center mt-3">
                                <a href="{% url 'recipe_detail' recipe.slug %}" class="btn btn-outline-primary btn-sm">View Recipe</a>
                                {% if user == recipe.author %}
                                <a href="{% url 'update_recipe' recipe.slug %}" class="btn btn-outline-primary btn-sm">Update Recipe</a>
                                <a href="{% url 'delete_recipe' recipe.slug %}" class="btn btn-outline-danger btn-sm">Delete Recipe</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>

                {% empty %}
                <p>No recipes found.</p>

            {% endfor %}
        </div>
    </div>

{% endblock %}

app/templates/app/delete_recipe.html
{% extends "base.html" %}

{% block page_title %}
    Delete Recipe
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Delete Recipe</h5>
                        <p class="card-text">Are you sure you want to delete this recipe?</p>

                        <form method="post" class="form-group" enctype="multipart/form-data">
                            {% csrf_token %}

                            <div class="text-center">
                                <a href="{% url 'dashboard' %}" class="btn btn-secondary mr-2">Cancel</a>
                                <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this recipe?')">Delete</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/app/edit_profile.html
{% extends 'base.html' %}

{% block page_title %}Edit Profile{% endblock %}

{% load crispy_forms_tags %}
{% block content %}
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Edit Profile</h5>

            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form|crispy }}

              <div class="text-center mt-3">
                <a href="{% url 'dashboard' %}" class="btn btn-secondary mr-2">Cancel</a>
                <button type="submit" class="btn btn-primary">Save Changes</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/app/index.html
{% extends "base.html" %} {% load static %} {% block page_title %}Igniting Culinary Creativity, One Recipe at a Time{% endblock %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'app/css/index.css' %}">
{% endblock %}

{% block js_files %}
<script defer src="{% static 'app/js/index.js' %}"></script>
{% endblock %}


{% block content %}

    <div class="container my-4">
        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
            {% for recipe in recipes %}
                <div class="col mb-4">
                    <div class="card h-100">
                        <img src="{% if recipe.picture %}{{recipe.picture.url}}{% endif %}" class="card-img-top img-fluid" alt="{{recipe.title}}">
                        <div class="card-body">
                            <h5 class="card-title">{{recipe.title}}</h5>
                            <!-- Add more information here if needed -->
                            <div class="text-center mt-3">
                                <a href="{% url 'recipe_detail' recipe.slug %}" class="btn btn-outline-primary btn-sm">View Recipe</a>
                                {% if user == recipe.author or perms.app.change_recipemodel %}
                                <a href="{% url 'update_recipe' recipe.slug %}" class="btn btn-outline-primary btn-sm">Update Recipe</a>
                                {% endif %}
                                {% if user == recipe.author or perms.app.delete_recipemodel %}
                                <a href="{% url 'delete_recipe' recipe.slug %}" class="btn btn-outline-danger btn-sm">Delete Recipe</a>
                                {% endif %}
                                {% if user.is_staff %}
                                <form method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-outline-danger btn-sm" name="user_id" value="{{recipe.author.id}}">Ban User</button>
                                    </form>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>

                {% empty %}
                <p>No recipes found.</p>

            {% endfor %}
        </div>
    </div>

{% endblock %}

app/templates/app/my_account.html
{% extends "base.html" %} {% load static %} {% block page_title %} My Account {% endblock %} {% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8 col-lg-6">
      <div class="row">
        <!-- Personal Information -->
        <div class="col-md-6">
          <div class="card mb-4">
            <div class="card-header">
              <h2 class="mb-0">User Information</h2>
            </div>
            <div class="card-body">
              <ul class="list-group list-group-flush">
                <li class="list-group-item">
                  <strong>Name:</strong> {{ user.get_full_name }}
                </li>
                <li class="list-group-item">
                  <strong>Username:</strong> {{ user.username }}
                </li>
                <li class="list-group-item">
                  <strong>Email:</strong> {{ user.email }}
                </li>
              </ul>
            </div>
          </div>

          <!-- Edit Profile Button -->
          <div class="card">
            <div class="card-header">
              <h2 class="mb-0">Actions</h2>
            </div>
            <div class="card-body">
              <a
                href="{% url 'edit_profile' %}"
                class="btn btn-primary btn-block mb-2"
                >Edit Profile</a
              >
              {% comment %}
              <a
                href="{% url 'add_profile_picture' %}"
                class="btn btn-primary btn-block mb-2"
                >Edit Profile Picture</a
              >
              {% endcomment %}
              <a
                href="{% url 'password_change' %}"
                class="btn btn-primary btn-block mb-2"
                >Change Password</a
              >
            </div>
          </div>
        </div>

        <!-- Profile Picture on the Right -->
        <div class="col-md-6">
          <div class="card mb-4">
            <div class="card-header">
              <h2 class="mb-0">Profile Picture</h2>
            </div>
            <div class="card-body text-center">
              {% if user.profile_picture %}
              <img
                src="{{ user.profile_picture.url }}"
                alt="Profile Picture"
                class="img-fluid rounded-circle mb-3"
              />
              {% else %}
              <p class="mb-0">No profile picture available.</p>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/app/recipe_detail.html
{% extends "base.html" %} {% load static %} {% block page_title %}Recipe Detail{% endblock %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'app/css/recipe_detail.css' %}">
{% endblock %}

{% block js_files %}
<script defer src="{% static 'app/js/recipe_detail.js' %}"></script>
{% endblock %}

{% block content %}

{% include "app/includes/navbar.html" %}

<div class="container mt-4">
    <div class="row">
        <div class="col-md-6">
            <img src="{% if recipe.picture %}{{ recipe.picture.url }}{% endif %}" class="img-fluid" alt="{{ recipe.title }}">
        </div>
        <div class="col-md-6">
            <h2>{{ recipe.title }}</h2>
            <p>Last updated: {{ recipe.updated_at }}</p>
            <p>{{ recipe.description|linebreaks }}</p>
            <!-- Add more information here if needed -->

            <div class="mt-3">
                <p><strong>Ingredients:</strong></p>
                <p>{{ recipe.ingredients|linebreaks }}</p>
            </div>

            <div class="mt-3">
                <p><strong>Instructions:</strong></p>
                <p>{{ recipe.instructions|linebreaks }}</p>
            </div>


        </div>
    </div>
</div>

{% endblock %}

app/templates/app/update_recipe.html
{% extends "base.html" %}

{% block page_title %}
    Update Recipe
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Update Recipe</h5>

                        <form method="post" class="form-group" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form|crispy }}

                            <div class="text-center mt-3">
                                <a href="{% url 'dashboard' %}" class="btn btn-secondary mr-2">Cancel</a>
                                <button type="submit" class="btn btn-success">Update</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/app/verify_otp.html
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="otp" placeholder="Enter OTP" />
  <button type="submit">Verify</button>
</form>